[project]
name = "synesthesia"
version = "0.2.0"
description = "Default template for PDM package"
authors = [
    {name = "Codeling&Decent", email = ""},
]
dependencies = [
    "bleak>=1.1.0",
    "loguru>=0.7.3",
    "pic>=0.1.0",
    "requests>=2.32.5",
]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.build]
package-dir = "src"
includes = ["src/"]

[project.scripts]
synesthesia = "synesthesia.main:main"

